import {
  overviewPillars,
  projects,
  experiences,
  labModules,
  philosophyStatements,
  beyondCode,
  techEcosystem,
  contactCommands,
} from "../constants";

/** Primary satellites orbiting the Orb — maps to existing portfolio sections. */
export const universeNodes = [
  {
    id: "overview",
    label: "Overview",
    description: "How I work across interfaces, stack, and acceleration.",
    keywords: [
      "overview",
      "interfaces",
      "full stack",
      "acceleration",
      "react",
      "typescript",
      "node",
      "java",
      "python",
      "ux",
    ],
    orbit: { radius: 0.28, speed: 0.12, phase: 0, phaseY: 0.02, size: 1 },
    mobile: { angle: -90, radius: 0.34 },
    mood: "calm",
    connections: ["builds", "timeline", "lab"],
  },
  {
    id: "builds",
    label: "Projects",
    description: "Shipped products and systems I've built.",
    keywords: [
      "projects",
      "work",
      "builds",
      "volunteer",
      "fwc",
      "ece",
      "weather",
      "ums",
      "react",
      "node",
      "firebase",
      "mongodb",
    ],
    orbit: { radius: 0.36, speed: 0.08, phase: 0.9, phaseY: -0.015, size: 1.15 },
    mobile: { angle: -30, radius: 0.38 },
    mood: "projects",
    connections: ["overview", "timeline", "lab"],
    children: projects.map((p, i) => ({
      id: `project-${p.id}`,
      projectId: p.id,
      label: p.title,
      description: p.eyebrow,
      angle: (i / projects.length) * Math.PI * 2 - Math.PI / 2,
      radius: 0.22,
    })),
  },
  {
    id: "timeline",
    label: "Experience",
    description: "Roles focused on shipping reliable interfaces.",
    keywords: [
      "experience",
      "timeline",
      "caterpillar",
      "fwc",
      "hmi",
      "java",
      "intern",
      "associate",
      "engineer",
    ],
    orbit: { radius: 0.42, speed: 0.065, phase: 1.8, phaseY: 0.025, size: 1.05 },
    mobile: { angle: 30, radius: 0.38 },
    mood: "experience",
    connections: ["builds", "lab", "overview"],
  },
  {
    id: "lab",
    label: "AI Lab",
    description: "Automation, agents, and faster engineering loops.",
    keywords: [
      "lab",
      "ai",
      "agents",
      "automation",
      "sdlc",
      "search",
      "hmi",
      "performance",
      "python",
    ],
    orbit: { radius: 0.32, speed: 0.15, phase: 2.7, phaseY: -0.03, size: 1 },
    mobile: { angle: 90, radius: 0.34 },
    mood: "lab",
    connections: ["builds", "timeline", "philosophy"],
  },
  {
    id: "philosophy",
    label: "Notes",
    description: "Principles I build by.",
    keywords: ["notes", "philosophy", "principles", "ux", "judgment", "friction"],
    orbit: { radius: 0.48, speed: 0.05, phase: 3.6, phaseY: 0.01, size: 0.9 },
    mobile: { angle: 150, radius: 0.36 },
    mood: "calm",
    connections: ["lab", "beyond", "overview"],
  },
  {
    id: "beyond",
    label: "Beyond",
    description: "Workspaces, sketches, and prototypes.",
    keywords: [
      "beyond",
      "workstation",
      "diagrams",
      "notes",
      "prototypes",
      "craft",
      "architecture",
    ],
    orbit: { radius: 0.4, speed: 0.09, phase: 4.5, phaseY: -0.02, size: 0.95 },
    mobile: { angle: -150, radius: 0.36 },
    mood: "calm",
    connections: ["philosophy", "builds", "contact"],
  },
  {
    id: "contact",
    label: "Contact",
    description: "Roles, collaborations, or a thoughtful conversation.",
    keywords: [
      "contact",
      "email",
      "hire",
      "collaborate",
      "bangalore",
      "github",
      "linkedin",
    ],
    orbit: { radius: 0.3, speed: 0.11, phase: 5.4, phaseY: 0.018, size: 1.1 },
    mobile: { angle: -210, radius: 0.32 },
    mood: "contact",
    connections: ["beyond", "overview"],
  },
];

export const nodeContent = {
  overview: {
    kicker: "Overview",
    heading: "How I work.",
    intro:
      "I move between interface design, full-stack delivery, and tooling that removes friction from the loop.",
    pillars: overviewPillars,
    ecosystem: techEcosystem,
  },
  builds: {
    kicker: "Selected work",
    heading: "Built products.",
    intro: "A few shipped projects—each with a clear problem, stack, and architecture.",
    projects,
  },
  timeline: {
    kicker: "Experience",
    heading: "Where I've built.",
    intro: "Roles focused on shipping reliable interfaces and accelerating engineering work.",
    experiences,
  },
  lab: {
    kicker: "Lab",
    heading: "Faster loops, clear judgment.",
    intro:
      "I use agents and automation for planning, review, and search—to remove friction, not replace judgment.",
    modules: labModules,
  },
  philosophy: {
    kicker: "Notes",
    heading: "Principles I build by.",
    intro: "",
    statements: philosophyStatements,
  },
  beyond: {
    kicker: "Beyond code",
    heading: "How ideas take shape.",
    intro: "Workspaces, sketches, and prototypes outside the commit log.",
    items: beyondCode,
  },
  contact: {
    kicker: "Contact",
    heading: "Let's talk.",
    intro:
      "Open to roles, collaborations, or a thoughtful conversation about something you want to build.",
    commands: contactCommands,
    email: "priyanshudhasmana007@gmail.com",
    location: "Bangalore, India",
    socials: [
      { label: "GitHub", href: "https://github.com/PriyanshuDhasmana" },
      {
        label: "LinkedIn",
        href: "https://www.linkedin.com/in/priyanshu-dhasmana-b7a12b1b6",
      },
      { label: "X", href: "https://x.com/PriyanshuDhasm4" },
    ],
  },
};

export const identity = {
  name: "Priyanshu Dhasmana",
  short: "PD",
  tagline: "Engineering isn't just what I build.\nIt's how I think.",
  role: "Interface builder",
  intro:
    "I design and ship interfaces, workflows, and tools that stay calm on the surface and deliberate underneath.",
};

export const springSoft = { type: "spring", stiffness: 120, damping: 22, mass: 0.9 };
export const springCamera = { type: "spring", stiffness: 70, damping: 20, mass: 1.1 };
export const springSnap = { type: "spring", stiffness: 280, damping: 28, mass: 0.6 };
